kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "runtimeclass-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runtimeclass-controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "runtimeclass-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ include "runtimeclass-controller.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io