kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "runtimeclass-controller.fullname" . }}-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "runtimeclass-controller.fullname" . }}-serviceaccount
    namespace: {{ .Release.Namespace }}
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ template "runtimeclass-controller.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io