nameOverride: ""
fullnameOverride: ""

webhook:
  runtimeClassNameKey: runtimeclassname-default
  tls:
    certificateSecret: ""
    autogenerate:
      enable: true
      duration: 3650
    renew: false
    certManagerIssuerRef: {}

image:
  repository: ghcr.io/jlclx/runtimeclass-controller
  pullPolicy: IfNotPresent

imagePullSecrets: []

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

service:
  type: ClusterIP
  port: 443

serviceAccount:
  create: true
  annotations: {}
  name: ""