name: GitHub Registry Upload
on:
  push:
    branches:
      - master
jobs:
  Upload-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          tags: ghcr.io/jlclx/runtimeclass-controller:latest
          context: ./
          file: ./build/Dockerfile
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}